[tool.poetry]
name = "clitool"
version = "20250825"
description = "A template for building command line interfaces in Python."
authors = ["tkcn568"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "^4.61.1"
requests = "^2.25.1"
click = "^8.0.1"
rich = "^14.1.0"

[tool.poetry.group.dev.dependencies]
sphinx-click = "^3.0.1"
stdeb = "^0.10.0"
setuptools = "^57.0.0"
pytest = "^6.2.4"
toml = "^0.10.2"

[tool.poetry.scripts]

clitool = "clitool.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
